name: commission_art_app2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^1.2.0
  image_picker: ^0.8.4+1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1
  webview_flutter: ^4.8.0
  shared_preferences: ^2.2.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/banner.png
    - assets/jasmine.jpg
    - assets/jasmine_recomendation.png
    - assets/dailymochi_recomendation.png
    - assets/dailymochi.jpg
    - assets/Profile.jpg
    - assets/splash.jpeg
    - assets/camera.png
    - assets/pen.png
    - assets/pengembang_2.jpg
    - assets/pengembang_1.jpg
    - assets/digital_art.png
    - assets/illustration.png
    - assets/painting.jpg
    - assets/sketch.png
    - assets/digital-art-bluedaisya.jpg
    - assets/digital-art-dailymochi.jpg
    - assets/digital-art-fidea-alipyani.jpg
    - assets/digital-art-hatsuu_t.jpg
    - assets/digital-art2-hatsuu_t.jpg
    - assets/fideya-alipyani.jpg
    - assets/illustration-trayofclouds.jpg
    - assets/illustration2-trayofclouds.jpg
    - assets/bluedaisya.jpg
    - assets/hatsuu_t.jpg
    - assets/illustration-cicigaleri.jpg
    - assets/illustration-drimixiuu.jpg
    - assets/drimixiuu.jpg
    - assets/cicigaleri.jpg
    - assets/illustration2-cicigaleri.jpg
    - assets/illustration2-drimixiuu.jpg
    - assets/trayofclouds.jpg
    - assets/sketch-claudia.jpg
    - assets/sketch-daninuara.jpg
    - assets/sketch-emma oliviya.jpg
    - assets/sketch2-claudia.jpeg
    - assets/sketch2-daninuara.jpeg
    - assets/sketch2-emma oliviya.jpg
    - assets/claudia.jpg
    - assets/daninuara.jpg
    - assets/emma-oliviya.jpg
    - assets/painting-cat-belinay.jpg
    - assets/painting-dog-Taller-Pintura.jpg
    - assets/painting-flower-amanda.jpg
    - assets/painting-scenery-amanda.jpg
    - assets/painting-whale-Taller-Pintura.jpg
    - assets/swanlake-painting-belinay.jpg
    - assets/taller-pintura.jpg
    - assets/amanda.jpg
    - assets/belinay.jpg
    - assets/check-mark.png
    - assets/background.jpeg
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
